---
kind: "operation"
client: "rug-cli 0.16.6"
editor:
  name: "atomist-rugs.travis-editors.EnableTravisForRugArchiveDSL"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.3.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "master"
    sha: "e43adce*"
  parameters:
    - "repo_slug": "atomist-rugs/travis-editors"
    - "org": ".org"
    - "github_token": "4**************************************b"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"
    - "maven_user": "t************h"
    - "maven_token": "A***********************************************************************i"

---
kind: "operation"
client: "rug-cli 0.16.6"
editor:
  name: "atomist-rugs.travis-editors.EnableTravisForRugArchiveDSL"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.4.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "master"
    sha: "ffa56d6"
  parameters:
    - "repo_slug": "atomist-rugs/common-editors"
    - "org": ".org"
    - "github_token": "4**************************************b"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"
    - "maven_user": "t************h"
    - "maven_token": "A***********************************************************************i"

---
kind: "operation"
client: "rug-cli 0.18.1"
editor:
  name: "mygroup.rug-upgrade.UpgradeFrom0_7_1"
  group: "mygroup"
  artifact: "rug-upgrade"
  version: "0.1.0"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"

---
kind: "operation"
client: "rug-cli 0.18.1"
editor:
  name: "mygroup.rug-upgrade.UpgradeFrom0_7_1"
  group: "mygroup"
  artifact: "rug-upgrade"
  version: "0.1.0"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"

---
kind: "operation"
client: "rug-cli 0.18.1"
editor:
  name: "mygroup.rug-upgrade.UpgradeFrom0_7_1"
  group: "mygroup"
  artifact: "rug-upgrade"
  version: "0.1.0"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"

---
kind: "operation"
client: "rug-cli 0.18.1"
editor:
  name: "mygroup.rug-upgrade.UpgradeFrom0_7_1"
  group: "mygroup"
  artifact: "rug-upgrade"
  version: "0.1.0"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"

