dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: PwhdJlkcCE1dj4fiTm+UlsEUOHFeGwCF8go4s/9ombdMUjQRqSuCKsL2x4AkYM1vYyE7oZJaQ39YJumP4ch4HXW7VmU5Dan4eR1JeXcB7y7Y1sLNxwe3JVMNedbev8ITNjUztbYpS9guqTilReUgAf83YU2fX4WFjnghiBkydIF1VOStJDjcPm+Mnc/jQP6kGcrL8uVBcxP6jhusPueJwbwxV/3u0I5AOV9WmhWLMPdJSRS656hIZJJPftMpkAgGPN94L1BM/pWaf5qNSLCTDUE77g1iItKePgqjqSPfpRzb2h/m1wtULUpTpNOHf4HzH0corDDXp4FafTEP5Q0PkqgoOWhTMRtHuEQVgTx6qlPXY874kCi4QurUmY5dJKwjSFn27tIjFIncF5WLM0slMPxqz1hsDff/O+YpLfJgM/2wkN13nnyPSJdafdTfSI8wLr5SyYuMr+APKQU+ETb6eayIPG7vl1nKI/cvTEYhXtHo0aGlZA3fmd9Ntt9/WlRmeO3eyRJrEjw0olxbqGr2wamo5leGSzOtkoCY4rHljNZpfGsmPJXOvNTzelMEQz7iSoQJ7gzNqtWQeS3/9Cr/DSKLgJwBfJ/zjhNTkQ1/zeJgALj0V/fAlayw/AYXCEZv16nolX6OEGvDK9mCLUJG/pDdiNUzfeHh9fx68dUS7xA=
  - secure: RFIErU6Sov8iGleHguOIc6qeLBPAWCtEYJBYQplwxe+uEmuDB7BPmy8Hh7in3zlPLXwE+ZkNx/p+HxwkpQmyS4/1xb+u34cY3yscKGQmoC2ECiFskWmQ2uR/cUdgOe2Yvqra6/6l6AUS5YmuSJZfGypOQdk/Rf1FGnvRMCgLZKSjN4i34V+GofxK1wjT+qPEFXeDZK9raMJ9kSosYRK2oZsX/B7SKPWvIaQ95FrEb6n/bjjRh8C2kj/4zYjyYbuPIcXFWFj2FA7GEjZsu8NePaDhYm+c89Sw4SUKkDQqG/cJqVzSv74URIKWgHacAirSBt2s/ggXJqunMEZ32DV8nfWqawBO6AU5A1Rw3/Z5/LH9sTQmhIbbt0EanOvDEWzscz44d5OlsPI5BDQHMkH4DiIi5fQBMOoNBzyXxaUcH5USJaFQM8CfcqRUW7VyLtm/66ZFPePcf9ETqhrT9ryKDsCEeqJ1ktOmwmiOnQtU9JRYmI0UnoZ58x3GbQh5/5C8oXr+aAr3C4DX18zMl3UF+oR+eg0qdHEyVtVEf4m5Jo/+1tDuOubhvMzmgfEB0lG1tL7Ht9H70ejL4e6O/nio+wCACbLBY4Q0XlqHu9JnfNmsKTIghHIT34rcTaw7oIZJhcqtNqAxms2pUisfxl/THPN67GVGqV7FO7H6mxicdeM=
  - secure: AGsmqQWR9MqZ4KUDEasr+uxsmnnXoFi/GQZgduSOoEhm39TmwjETklbaT2gjSfAEiBMAhl1vroy70PEc9HaLlOwciHT6XWbwtAabYFBPY3AYi0Xn/XYAWIGxALYCTcG+Zgt3n/IQ7AEDKpzzSMDyAei2KZfhodXdYI54W7f1R3qsQV22gjz5qUIiVVwdn7nEp+T6oGUEWAmE4jDDAL3FlBXJ3I1gv/p+iv6v8yVqzAZggOmIcozBWbb2ULNEeL9cwC2KbrBIml1Og8fjZjogK06V9kA4vhxukg7259gWsTFFnk9XFGq924kbUKAdkcBKNdXxXesVcUmuBgjp+nX2+u/3lYRxWqUxQc0XWGep2iTUs7wze1gryQgrbSBgK5Er4WUfsmCGY7UtN4WUZ+cMss2DgEuJCnfqpwHkqo9tmsOcc2J/lZkFR81fKQV+8AdOBopMI6QnOL49ey/L6T9Qq70kLztkpixnxlAv8d0+m8XwO576hS1LKCCZvcxgDCqoYjPhkhn/+DBaAIucyWXU36GwXXrkGvOKv22cLz9XfWfnetn0Qefw/ygWPI4nPjgzkZZNkjsoIMpcB0RsMT6e8X6wKEKIqMjZfQ0/LGju1Jfmlu0i93yOJJjvatXvTE7RgP1xO3W7cVu20k7tBdAZcFIhF5awsaGxGTfIKGA5/ps=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
