language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - secure: ExXYKO940I/JK2ppXhSJ/pAoDgiKYdYQo4lrhU7iHnN7vjB31u+yasLRy5MBQaNnjJs5O2BEXSYZVU6Rt3UZuR5NYk25i+Bf9Sw/ppyRIr77YpF5GiFl9U41oSFhwxc8WcLkjGXlXC8DK0fiwyG1MR9FO53XkTv7FNsFVLxPYSjVnSNQ6dzU8vaA8LtYi9VPNIkGzdA/88GGWWJnm5nE1Bcmv1tChDNQqchLCPZI80x5N/EK0/uITEpW+YkpeFaC3o5CHxq/ONOA6rIfzf3XkLdIUVQDTkXhPzoyH+m9dMEb3xdJhzpniDQI2wCwVaaBryYzbX6USyEq2QpJ6n8+Sd3fsa026oZwHsoXCEArJZawADo7WbnfJeLp1lf6/po9Rt2RkyF+Xl675aBToKPK+13NBo4zk3d3/uFFva/IT0HVlOdpVHvBP4+QJbPvYmVYiyV/8WI+WRf/LTRfVCgHpOXKWWKqmRw8rNHM8UCNEr2H4sJ0d+kmeIil3YOwyQNRdKoAkWjyQU+7KI/cN35h1k2o4G93rsjjT8nEkQdqoJ2nOUl9F163U8gecfojl4eNDSSXt148DE/vWEjMqY+PRXnY7K5/CXv2rbTAimL9H9CAgzDmmi1oyBdw1maxE1+YNe9wtw+Wa/+6g2qJzQxX588Z565bkUD03yArhS9JvZQ=
  - secure: e6S7fyZfoR1g8KolkuRCc8pdCDrqYZ5MkDeqtwpAM6tDiurzfnzqbEia+v4G16Y7euWYsgx0lDGtu/DLjLcA5ORexIgpAy5ODNY2X3EO/PjeXgTDL7Nitih6hap3eLfh1cHatco36+jdl8RJORFrdVWM1DgBvg2h4XnJbzdnWSNZHW9t+eHDVkiM7qC2iGXd7abyYc1eIhgF2fA5zTLSYVh8bin6V7X9uJxRo1PkC2Kzw6vicb6B22M3WwCsCqGiEjg7+/WhypgzB8TYl9vUmbly6cf3n7Mna7hg55pO3AXPAt54c1ziYYhcsRiqEpIRWhn2B6hHwrYgDFqSJ6n+IgnMByCB+jg9vftmIM/J6Mw4D3BdM7SFbcVQw1Hj+h+ZxbBIuqDAvDBpBLuBpAy+MawuoiX2OLVW0kBlELhkoZYVy0JmNRVTUpiGbk+n/haoDgSmewETUUkWEF8cG1/yv64D7oCyLjSf+ibsfJNWiBg/XgNHuxvcbNYjtE3bg3AeuiqSQtoSL2hgW4aVM2oM2lBQsJKSGoepE75KG2apPmS9+5wqC4M8J/2pORX0D0UVwDfyro2NlDaWiLow8UGDZ5HQ/Iz4zYloPCBDoVSFx6SHSDD3iLPFzLV48oOPfz5pc1AHzUKyNDJNgy+e5MA2Fg6GNoWNFNfK62jpI5SRVsg=
  - secure: YL/yZU2xBufcjTIf+ajH0jNSZvrujsN6X9PYD0yQo1P4H6MOc94TIoz1x0sO4JUAIFsGLEptcisn8XKMLRPYYVNwaHIa1GHhd0uG3X91dS6qt7aJBT7Lfi6BndTy+VrP7ELuv7CxEjcK9R7NLAVNPmbOphppdTrUmp0mOh9wJZK+By8Z1k86YXEYD4En3Lx562gNcefBNmp7hCWo98BLF5Nbt742/dCkz/ESfLl3GZAI+durPpVQZ7css+fjV8+GdD2VNPjdwbNR7bO0cIAkzW3uOtb/U22SvGmMrEdGmx+PcS1woqoS503LYp9CrRqkMlezSFo2DdtyjR5cVV/Vjnz2qvnyffpv2zG7hpWpbRJrcRDq44oMd9IOgiXLNY1nNU0X8OvYB/GEfTR7h8ZSujrVSajTRUcQa79p5mI2KMfUd3JYnvu8EFHRztGDplC0cAo5u5kfZpf2MBP3U0WxLsV2Lq9cRfj1aeVHeNYN8HpWVUKAA9GSN2E1EtYFQ5ulxqUsAnMQxjZrgHzfApKX5Ey8ZPsJjJkqT7i8b/3vrfWSFBk7ahIfsrE1S7zsS9To0fzSlXPgWhWEN64nSAqmTvji37aZZirjx3qoIHw1FhhGNFc8WEAOqye+WFOurTqAVdOteZhHqKwCBXKwEBi0jOomljtlc3Fkz9dxX+QVMic=
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
