language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - secure: OXjv2TVuP1qpRrLRUXpiQcMFoxRq0lSclt6UeW5xrAPkLnKGf2D25AgnFhN2EUsJ+nsQ+uSmawbqYngUvxciKnQjdLBJuAxW/B3UugHDYJAN5Ro0vAdczxWnlnyjTnNvZ/P5+fSpWmhNeVT6lGmvSz336vUphFWyKcC579Rt55UJYBaYso1k+1FEiLMJPuyk3g8hPYhXVoGpnA1I/F+HdUTZM3BBeFcVN4ESMez+6aIqrNAWXrFK1bML6KWizvYOqZ3CD4VvxMWQK0LEbBK+o9HES0Y2pYvNXewMQhYMFXT5iXmMLSvOecXkNrocimSr0x5gzbv0g5oljIvctxVrdRp1zkjTbq9znwd0eV0kfv6JwlBsyJL3Tx5adsBsYbHVJuRiEBJYiGCS4VrPcj9wK7UhBS1NKK2mwJz7NEiy+4IgnUzTadWJrP067EEQJ+mx9N1jXbvp7bNdIHBSJ7AAt4B7lISnSiZv8c4xAI/LBQT2wNZ7OkSFodNv3BwfGLMutGnLXXMuAfe+rXCmWuAHnutKd03tEEouArX4U6zlqXLoAf2MQyDOAedp4f+kr5s6TJk1jgZQYuiHXjKw4LyUaDPjToQ3KkKVeRY47s2cT6FOuUP0DcECkdQBGuIuE9PTsa0NbP54O1uooiCfAYNHCcW3DWOaP49kPxRXSCMleY4=
  - secure: Lj5B3ff6q13QsJfYUOFn2LjNDmy3DbXeVu95l75Gzqoi3DxXaY1lIxdEBuUXX5p1legUY6zpcEa3RJRVcvZ53cM8THz8wArQaQh1ObpwAgjrHY3RUE1ajJiYCrd59OtdlRgF6zvB4PZd3+uV1Nlq61/MaqgIQtMBTC01rUvguSxgFix7BopqBR+BAZqAbzucilb3D/gtIN1d0TifdBDzlgFFGPKbAEZT9JtaqvSBeYmQ1tOZ7ZOXy027royw2q3VRFe44S9SrooWxr1AtrlMDVEBlEbbXfBn9ubrRcXYETIxEefls1G2/EI1RhskoYxQlWXRa5imOW4EKBaWdie3valJxufmHNrqdfE/unh84Gq6qYLjT1+dola8k6Zu/w+l8R4Ki6/luwUXh3XOkUCQDM1ZijPVzbesd2ZceyxVzLQAYYSNbSMkSIlGiggCF4bz05MMdUdNA4xDJiZwlKIACv60UWMz93ZJ6t+6TxoV+Pp1RvKgiMStGU0jyxsJmDzMXF/5fNVvoPRrD2uFt5h1vJRhtQ0UHdWXlNM1pXqOtq9itzfTMEOdrfRgIZlsHJ0/f6HemCmDqSqyrAAqKEVwyPu4999B6CwlyQlQu28BQtcEoFm4A5r+/dwEbbg7heOVRoilbXcyK4nIYBg2M7/gOPACDsrdMR9mySds98fiOvg=
  - secure: yk20+xJl/6Fezr85sRyZf4rb8wfv+2Q1RONnaLkkmeitq+f/koCp8Lo5YvosrFJsVA4Jzai8LSFbcnkhUuBsgBKjTJV6+/Vkql1Sl8i3JGk7IV20dKdqvYj79yUhguy0a6Ww7RlpRfLoc2vWh8VtR/9l/ZvqUgH3eoJR9v6mHOmxXSPkPvQoCfgFSqvJmcyvhYHJspAxWzQ1zgRYUkpKoJIF/X03lxVcnvQmOwkZlES4T/d1wS2oJmy/pJnE23H5xrYAatfz8xxbokj5tivFvbbgjfab3SQuoGdM42k4pLjJkKbVxWS11eDjbbabbewaa6m5WDx6o9jG1AJW1U5yoce2XbQQ6kgLj0pL1wVR7xTuJ0k9LQfzkSdw2TYZtbgG32xAiAT3F2z/IsBOCfjvNsfM0DMoVEfqLGhQwvk5xiAwafXWhqUV6TkToqwKsDSCBK7E3oBeWMRPtkvqLUH//DXnXf3wi+UC0HuFWXXS8293i85V/mH9I36hXtTorPsyLJ3T/2c+Cpetv5y2aUkKZfkFnEYh6bvq9OZWL6X8NZX3WjX7TZU/F41SQMiczVxq8Yj36mRm1jdLaXBZecC5B4bJlzWzfNiYLzgqjWYNCMuNhSfNCZbAIqOUYfHqqtSOwlt/bmypJHsTDT3IvIBR0aEHf3MF2baZpCwG5ko6co8=
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
