dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: 4QnM51HGC25WNm8SdbxSZPP3mspKKTdoIUYIt/M10mijblyBC1qkGonmKyZ1imp1oi+w/CXjXTczDsoGxq+UJ4uiSkD2FUERindOQUKYCYSYISgk3uA3h8nkiGi6cpwRwlal4U7XQJeKzAFOp3ttLTDfFLG5QZn7hZNFXsInDd0lqRi4vF0EzvY9UORbcjrvD4x61vI42y6hINp2fhpqEBRWzoEItHau4+Jd2JqzLq5QN/R8RR81zemcQpH0vcD+IZgPp2CF3NAkZ4leTcWSHxZM2OWqg58yaC0U6Jz7Zs3+67MDdM97CFmAr4+65/Ji4RkzFQ6CRCxW6/AgvoYFDXLjTSaqQDJiNZyPRG5b6OuouEq4Zl3K8xZCKSlolHCoSmT9Y/2Fuk4qf1WLo2TmEtReNgybMUqDlzbH10TJOhpmDY04+y/KxDTRKqVIvdDzSmYPVnMjX09HTNBhKPD91N7Y0FP+w5pFQLRpv6bTxJI6dAU1xUKX8XcLJwEjZ5upkQonMJjrv09zugL2s8Rvqf3uYco6H2PczBJBmJ91BYgg2pUf2UQIHHKWEADbrnbhYGExcmBlB2ysyqTHNq1viaHpkYmorr/YpZCl8zKm3K2tSNo52rmZGSpFFMJUhlUt2IhLm0xmkAwY5DCuyqeC/M+vm6K/kFhOJze9/9aje6U=
  - secure: jhz5M9vmYhC2C5gjXUk76eG1LGoVlaakMPBEb5wfZMLix14gBu6uKPpat+Ei//gxGQk+KTfwClWYdPCUeKvzAOHXUvn2Mp3vFwRYd2nw5Je0LBz/nCf/IhJHkyMetv5fOpnUicG5EHp9itrqc1t9BzmXQrkGy22+jUlImB06QB2lQlb7tQ+uy4OOCGA1wQ+wCVGqUkAIvvd3gLCsDu6tbK9f83pJzQvG077oggIvCHG0aAQ5I55Ao+Aee15SkxnkaDHBGD1VavhDIbfThgdafrhtv/xKsSDGsLlNgtUptpT3hwGiEKWSpsM1I/hdBF/VllqeWWXftqzzXr9olWlF8tSUyrn9yEfJRwsi54hEhfYRy3XXWLI6N5qqlyrSvOygInigGRPyACHh5b88jS6FoXBE5IO3pIAwx0wY7NsuxR2okofXfPQN9R8x6XhTPBhne/Y5Fbsb9p0D6C0q9d2MCRAVt03KmXek53Pe+7Xf+93NfaYIBt9V5/+i3+ltdb6C4jy/dzzL03mbPWujHbSmyiGyRTDvwNgE6sbXfUutH0//qxnidcuoG0WwypH9FmvQ8NETazY3Kk5s0uPHpX4lbiF4SuKzrUOuz4L/FYDUIVR8QQ38MJTl+ao3iuNfSmlLb82NsfL9k7TFE8agMSf/yDAXuClM4EQFlkLeSMTSoT0=
  - secure: gV7HR9l88FsntxY6dt6NL2lAT0OBXzRFyWZzsCVPb5fGnBayhPXtPPrtTQgJJ/5DkAPhLBFc+bVOUJj7mXTlihNZWU8WjauEnbhUD3jLhM2hOW1s4gZaUt3rG1BD+BK201Kaqq3a74r+03aKR/s1ROR1TlurrYkqjTqOQjlo4LMn94EFB+sgpiRaFfVc+txDcrosF0abuwaKaj2SvIgg6ljvlMjjSa0mDj6GHPeEucrlxhfqeT7wQrnDoCNGvPZtuJhDsTG2jLzMSWmKK76NqOoMkF0YF8TJrdyK1aTvi6kNcr44mLOfvW25w433JWsp2ZTes8POaMPUcAqDT8fU/jHpG8nVqHogciEUIKN0CkRq+3XOHO4/WRFsVLuETcOl/3CldZzcLRq504P+K0u9yUjWblBqbzqu2PLFjq20Pp9ekjtCWZZqNFb1j4TfIcxivbqp4GvCDFUWGKVZ8/MyftvGgQ1SEaG0DvS68Qj4axPrVK9x66u3LOMYGRWoIyLZ6F+g9/tRL0xkyDNuEL3RCp4c66GsOq6Gtbdrl7alBNHQ8+XpzMSc3iXkdZ7Lr3e7kQAn+HaE1JNyXdgR7tHfzYNfkvYwEB8k6tf8KLEyjeZ0xr7StoN44Ciyh8lfM38m7csmUevG1qbANXyG6666PzdAWWinZ5FGQTFbqWXN0Ag=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
