dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: B9BCIIW9uS8A9P7d4lBGWfG/HOAFECbzyC+H5wuOYcgH+FW3+jMJ83zJceRfq7OhiqmFNMAaqoDpQD4SmaCpFa1/akYNQKieo7+wlOLcVuty6cqdKbKwr6liL3ov8/vdwOMgF2doJFjnU0xK4jYAwt22bONF2R4xP0c+1K959MIHi+VrpQvE45wliK0b/3l8RJs9SaxfYUUHHvyeTg0lR807zBSNF7RggysRKE+bOlysEzn+StbhGWG9SwTUZGeW0kadi4MMhogyZh9xTNJUpnNx1z6kZzU7yJjbAXMQF9DyrEQedwu+D40xga5IrgybBACsohYfCy5MyK+3xIxqHdTXaJBKLajESLNaoUxRbioHGKztbPWfGhScv6O+fOlpdfFfOgw36FXJzo3JiRSnl38imf2tGak4AcgU4MC550baHrUlnbQd8zJkOx0J6sKteeAIFOebajxVrvt679brBNmX/8sNfOYhs53tce79wgxPsNSVOgA2gQNvlSCcsVLMlhxpSM8z1JTlQEeCQr0ZDBFUBIZkTgo/4SNHOo9jpenqqa1AnEvPHNLe2++AXbuT2NQNFoVAuluS7tCWeMsgKbOjmQ/JVFm16eZJLxno1vxMX/3vpA+MqkWVGE/+2wNU2i4wKtkwKldto8vSZXMFqR8SgBavpaZoFwxhH8RDoZ4=
  - secure: wiif+sJRu49r+EdVV6mLeOeCajDOr+kZgNZjDXnV2gbdPXfYPnOfikzG4lIqyfDwc5ZU6UTjPUz//dX2gFa6xhb7XRh+muQY8QJkRTTqVOoNCE/lHXAu6Aw2Ah0Bem6ferAjoyELaN+cBllAjdGk4WDmpMNPV25Qb1lyiubVX7c8+qLpohneujOoU78Op8iCYIZ0GkCkUWft/jxWRG+X3XBkB2Y+fc3pfOGBU6IUkL2xa0y+WSJsGwECQMbj0xFVEiAH/5YgyshsmuXbUuCUXlC3MTvK+ffH0+1FFFuSJeQdEE9dXfKXcDc/eEeJeGVrEiP+BzlylX4EIXgIbfGCFLVi5UUf7Uo/Z3VbOOsCcJpkBih/PZcYqqzAEypIDatwyP8BHLDUut7+TEVonM8SHVwqbw0f1TlqIhvnPJMNmYw2AmUMAFhjpka51Zfik5DGIevlpRx1g6PSsvodVpWnoMRTjA3PGkaQQVKjvJkGqxJ7A1vV2P627L+kO0yJCG4C65p3BmHg54MLc/XnFdMVtI4uGl1vv9pvrJKN0jxaT9wYjA5kvTFO+x9Y4/sqXUYFZ/4kDqetg4X4OQzp327/8h1pBQKnA33n7BaN71eMb4VqHOSUFhpGg9EpfNlb+y8G8MhToaNQmuOFTyNeAPUF1oX4x9w2ek/BHMJzQZVqmuM=
  - secure: 0rdhkO5ViAqSYvG7/JoUeAuyGu4PhRxlLMcrZBZO83Tr0ESCtDHRIaMwygsSkqF+4mw+ItsxyNNFsbVvOYnc42e4H/UPGAAhb6DqAjTTsgof6hKHy9hxq+JalU09jLQVrkaA8mnYaneE6wjJBcuU7EqOCH6mMabY+PoVNBnNj+50qX/5Q47Vf3s61pPFbxAyLJWrdpJyp9hxU6ai5ZxHgn3cRTjytCHrBqaRWi6h1Ir47pq0V0ZdzgdYJYPXi7MWK1zn70eLMDn5NmWTxRMPeQwUZG6CCSRXkWuOH+6wlVkr85Uj1q46HS/fPQb2f+OoSiAh0smnFD4N0l3mbLzdzf1qh1YkoE+aLv193GIq4jUxwy5JFBPATOp/9CRCPUR9ugag0aueSO/EV5vfpWZ7vHdfqCfaYhYM2Ydu3rQaLcuEeOowE7TVtI/FMIFlBlgnbN1M3jZUat1nd7OIMcMdQrkjv1VQ8FzP6kEn8UDJVvgIRPUn+FAkv/TrPZygeTszlf50GAlChQhQIFRASu1fGebfhS+OQ2Ja5CmRMN/3soD2+06y5ZKesSyow3iD547dKyU2U52siIZtxNRjUYxj+9LmA5lK5ZrELT0PLZ8c+S7GfLQb5J+O2WMGGHcf84X6MEt1fBX5we5Q2oCRlvbywx9z5uHgzFCiSaMIKLCAagk=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
