// Generated by Rug to TypeScript transpiler.

import { EditProject } from '@atomist/rug/operations/ProjectEditor'
import { PathExpressionEngine } from '@atomist/rug/tree/PathExpression'
import { Editor, Tags, Parameter } from '@atomist/rug/operations/Decorators'
import { Pattern } from '@atomist/rug/operations/RugOperation'
import { Pom, Project } from '@atomist/rug/model/Core'

/**
    ChangeDependencyVersion
    Change the version of a maven dependency
 */

@Editor("ChangeDependencyVersion", "Change the version of a maven dependency")
@Tags("rug", "maven")
class ChangeDependencyVersion implements EditProject {

    @Parameter({
        displayName: "Dependency Artifact",
        description: "the dependency artifact_id",
        pattern: "^[a-z][-a-z0-9_]*$",
        validInput: "a maven artifact ID"
    })
    artifact_id: string;

    @Parameter({
        displayName: "Dependency Group",
        description: "the dependency group_id",
        pattern: Pattern.group_id,
        validInput: "a maven group ID"
    })
    group_id: string;

    @Parameter({
        displayName: "New version",
        description: "the latest and greatest version you would like to depend on",
        pattern: Pattern.semantic_version,
        validInput: "version"
    })
    new_version: string;

    edit(project: Project) {

        let eng: PathExpressionEngine = project.context().pathExpressionEngine();

        eng.with<Pom>(project, '/Pom()', p => {
            p.addOrReplaceDependencyVersion(this.group_id, this.artifact_id, this.new_version)
        })

    }

}
export let editor_changeDependencyVersion = new ChangeDependencyVersion();